In [29]:
import numpy as np
import scipy
numpy.version.full_version

a = np.array([0,1,2,3,4,5])
print(a)
print(a.ndim)  # 维度
print(a.shape) # 大小

print(a*2)
print(a**2)

[0 1 2 3 4 5]
1
(6,)
[ 0  2  4  6  8 10]
[ 0  1  4  9 16 25]


In [11]:
b = a.reshape((3,2))    
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [14]:
print(a[np.array([2,3,4])])

[2 3 4]


In [21]:
# 无效值
c = np.array([1,2,np.NAN,3,4])

np.isnan(c)


array([False, False,  True, False, False], dtype=bool)

In [28]:
### comparing runtime behaviors
# dot() 矩阵乘

import timeit

normal_py_sec = timeit.timeit('sum(x*x for x in range(1000))', number=10000)
naive_np_sec = timeit.timeit('sum(na*na)', setup="import numpy as np; na=np.arange(1000)", number=10000)
good_np_sec = timeit.timeit('na.dot(na)', setup="import numpy as np; na=np.arange(1000)", number=10000)

print("Normaal Python: %f sec" %normal_py_sec)
print("Naive Numpy: %f sec" %naive_np_sec)
print("Good Numpy:%f sec" %good_np_sec )

Normaal Python: 0.507283 sec
Naive Numpy: 0.574766 sec
Good Numpy:0.009433 sec


In [30]:
scipy.dot is np.dot

True